var content = [{a:"Malheureusement", b:"Unfortunately", c:"Malheuresement, je suis ton enseignant. Mince.", d:"Unfortunately, I am your teacher. Bummer."},
			   {a:"Fevrier", b:"February", c:"Nous sommes en Fevrier.", d:"It's February."},
			   {a:"Coquin (m)", b:"Rascal", c:"Cet homme est un coquin.", d:"This man is a rascal."},
			   {a:"Grenouille", b:"Frog", c:"La grenouille saute.", d:"The frog is jumping."},
			   {a:"Autoroute", b:"Highway", c:"Je conduis sur l'autoroute", d:"I'm driving on the highway."},
			   {a:"Pain", b:"Bread", c:"J'adore le pain avec du fromage.", d:"I love bread with cheese."},
			   {a:"Portable", b:"Mobile Phone", c:"J'appelle ma mère sur mon portable.", d:"I'm calling my mum on my mobile."},
		       {a:"Réglementation", b:"Regulation", c:"Cette réglementation est strict.", d:"This regulation is strict."},
			   {a:"Grave", b:"Serious", c:"Ce n'est pas grave.", d:"It's not a big deal."},
			   {a:"Vide", b:"Empty", c:"Mon ventre est vide.", d:"My stomach is empty."},
			   {a:"Dernier (m)", b:"Last", c:"C'est mon dernier bonbon.", d:"It's my last lolly."},
			   {a:"Grande (f)", b:"Tall", c:"Cette femme est grande.", d:"That woman is tall."},
			   {a:"Nouveau (m)", b:"New", c:"J'aime bien mon nouveau chapeau.", d:"I like my new hat."},
			   {a:"Premier (m)", b:"First", c:"C'est la première fois.", d:"It's the first time."},
			   {a:"Vivante (f)", b:"Living", c:"La fourmi est vivante.", d:"The ant is alive."},
			   {a:"Chose", b:"Thing", c:"Cette chose est étrange.", d:"This thing is strange."},
			   {a:"Envie", b:"Desire / Want", c:"J'ai envie de courir.", d:"I want to run."},
			   {a:"Histoire", b:"Story / History", c:"L'histoire de ma famille est belle.", d:"My family's story is beautiful."},
			   {a:"Langue", b:"Language", c:"J'adore apprendre de nouvelles langues.", d:"I love to learn new languages."},
			   {a:"Personne", b:"Nobody", c:"Il n'y a personne ici.", d:"There's nobody here."},
			   {a:"Semaine", b:"Week", c:"J'ai été ici pendant deux semaines.", d:"I've been here for two weeks."},
			   {a:"Besoin", b:"Need", c:"J'ai besoin de manger des fruits.", d:"I need to eat some fruit."},
			   {a:"Escaliers", b:"Stairs", c:"Je monte les escaliers.", d:"I'm going up the stairs."},
			   {a:"Médecin", b:"Doctor", c:"J'ai besoin de voir un médecin.", d:"I need to see a doctor."},
			   {a:"Patronne (f)", b:"Boss", c:"Ma patronne ne m'aime pas bien.", d:"My boss doesn't like me."},
			   {a:"Rapport", b:"Report", c:"J'ai besoin de soumettre mon rapport.", d:"I need to submit my report."},
			   {a:"Tout le monde", b:"Everybody", c:"Tout le monde s'en fout.", d:"Nobody cares."},
			   {a:"Drôle", b:"Funny", c:"Cet homme est trop drôle.", d:"This man is too funny."},
			   {a:"Jeune", b:"Young", c:"La fille est très jeune.", d:"The girl is very young."},
			   {a:"Malade", b:"Sick", c:"J'étais très malade hier soir.", d:"I was very sick last night."},
			   {a:"Pauvre", b:"Poor", c:"Aujourd'hui, j'ai aidé un homme pauvre.", d:"I've helped a poor man today."},
			   {a:"Sale", b:"Dirty", c:"Ma chemise était beaucoup trop sale ce matin.", d:"My shirt was way too dirty this morning."},
			   {a:"Triste", b:"Sad", c:"Je pense qu'il est triste.", d:"I think that he's sad."},
			   {a:"Faux (m)", b:"False", c:"Ce n'est pas vrai, c'est faux.", d:"It's not true, it's false."},
			   {a:"Ancienne (f)", b:"Old / Former", c:"J'ai adoré notre ancienne voiture.", d:"I loved our old car."},
			   {a:"Cher (m)", b:"Dear", c:"Cher Monsieur Jones, tu déchires!", d:"Dear Mister Jones, you rock!"},
			   {a:"Contente (f)", b:"Happy", c:"Je pense qu'elle était très contente hier matin.", d:"I think that she was very happy yesterday morning."},
			   {a:"Humain (m)", b:"Human", c:"Nous sommes humains.", d:"We are human."},
			   {a:"Jolie (f)", b:"Pretty", c:"Cette peinture est vraiment jolie.", d:"That painting is really pretty."},
			   {a:"Quoi", b:"What", c:"C'est quoi ça?", d:"What's that?"},
			   {a:"Aide", b:"Help", c:"Au secours! J'ai besoin d'aide.", d:"Help! I need help."},
			   {a:"Geste", b:"Gesture", c:"Il a fait un geste symbolique.", d:"He made a symbolic gesture."},
			   {a:"Bisou", b:"Kiss", c:"Je voudrais te faire un bisou.", d:"I would like to kiss you."}, //// needs proofing from this line ...
			   {a:"Fleurs", b:"Flowers", c:"Je vais lui offrir des fleurs cet après-midi.", d:"I'm going to give her flowers this afternoon."},
			   {a:"Bougie", b:"Candle", c:"Cette pièce a besoin d'une bougie.", d:"This room needs a candle."},
			   {a:"Gingembre", b:"Ginger", c:"J'adore la bière gingembre.", d:"I love ginger beer."},
			   {a:"Poivre", b:"Pepper", c:"Peux-tu me donner la poivre, s'il te plaît?", d:"Can you give me the pepper, please?"},
			   {a:"Allumettes", b:"Matches", c:"Papa, où sont les allumettes?", d:"Dad, where are the matches?"},
			   {a:"Livre", b:"Book", c:"Je lit un super livre en ce moment.", d:"I am ready a really good book at the moment."},
			   {a:"Poêle", b:"Frying pan", c:"Ma grand mère m'a donné une poêle pour noël.", d:"My grandmother gave me a frying pan for Christmas."},
			   {a:"Forchette", b:"Fork", c:"D'habitude, je mange les frites avec une forchette.", d:"Usually, I eat fries with a fork."},
			   {a:"Nuage", b:"Cloud", c:"Je vois un nuage qui resembles un cochon.", d:"I see a cloud that looks like a pig."},
			   {a:"Brumeux", b:"Foggy", c:"Je pense que c'était brumeux la semaine derniere.", d:"I think it was foggy last week."},
			   {a:"Soleil", b:"Sun", c:"J'ai bronzé à cause du soleil.", d:"I am tanned thanks to the sun."},
			   {a:"Chaussons", b:"Slippers", c:"Il fait froid, donc j'ai besoin de mes chaussons.", d:"It's cold, so I need my slippers."},
			   {a:"Lunettes", b:"Glasses", c:"J'ai acheté des nouvelles lunettes.", d:"I bought new glasses."},
			   {a:"Horloge", b:"Clock", c:"Pour savoir l'heure, tu devrais regarder l'horloge.", d:"To tell the time, you should look at the clock."},
			   {a:"Baleine", b:"Whale", c:"J'ai vu une baleine dans mon rêve.", d:"I saw a whale in my dream."},
			   {a:"Mains", b:"Hands", c:"Tu as des belles mains.", d:"You have beautiful hands."},
			   {a:"Pieds", b:"Feet", c:"Mes pieds me font mal.", d:"My feet are sore."},
			   {a:"Cheveux", b:"Hair", c:"J'ai besoin de couper mes cheveux.", d:"I need to cut my hair."},
			   {a:"Nez", b:"Nose", c:"Sur cette photo, mon nez était cassé.", d:"In this photo, my nose was broken."},
			   {a:"Terrain de basket", b:"Basketball court", c:"Je vais jouer avec mes copains au terrain de basket.", d:"I'm going to play with my friends at the basketball court."},
			   {a:"Escargot", b:"Snail", c:"J'aime bien manger les escargots.", d:"I like eating snails."},
			   {a:"Cou", b:"Neck", c:"Vous avez un coup de soleil au cou.", d:"You're sunburnt on your neck."},
			   {a:"Cheval", b:"Horse", c:"Peux-tu voir le cheval dans le champ?", d:"Can you see the horse in the field?"},
			   {a:"Dentifrice", b:"Toothpaste", c:"J'ai besoin d'acheter du dentifrice.", d:"I need to buy some toothpaste."},
			   {a:"Baignoire", b:"Bath", c:"Oh la vache! Le chat est dans la baignoire.", d:"Oh my goodness! The cat is in the bath."},
			   {a:"Mairie", b:"Town hall", c:"Il y a une marriage à la mairie demain.", d:"There's a wedding at the town hall tomorrow."},
			   {a:"Micro onde", b:"Microwave", c:"Je n'ai pas le temps. Utilisez le micro-ondes au lieu du four.", d:"I don't have time. Use the microwave instead of the oven."},
			   {a:"Frigo", b:"Fridge", c:"Il y avait beaucoup de place dans le frigo ce matin.", d:"There was lots of space in the fridge this morning."},
			   {a:"Congélateur", b:"Freezer", c:"Il y a trois kilogrammes de mûres dans la congélateur.", d:"There are three kilograms of blackberries in the freezer."},
			   {a:"Torchon", b:"Tea towel", c:"Mets le torchon sur la table, s'il te plaît.", d:"Put the tea towel on the table, please."},
			   {a:"Fenêtre", b:"Window", c:"Il fait chaud! Puis-je ouvrir la fenêtre?", d:"It's hot! May I open the window?"},
			   {a:"Cadre", b:"Frame", c:"Tu as beaucoup de cadres sur le mur.", d:"You have a lot of frames on the wall."},
			   {a:"Animal de compagnie", b:"Pet", c:"Est-ce que tu as un animal de compagnie?", d:"Do you have a pet?"},
			   {a:"Chambre", b:"Bedroom", c:"Va dans ta chambre et pense à ce que tu as fait.", d:"Go to your bedroom and think about what you've done."},
			   {a:"Maman", b:"Mum", c:"Est-ce que tu as vu maman?", d:"Have you seen mum?"},
			   {a:"Bâtiment", b:"Building", c:"Il y a beaucoup de bâtiments à La Défense de Paris.", d:"There are many buildings at La Défense in Paris."},
			   {a:"Boulot", b:"Job / Work", c:"Je vais au boulot.", d:"I am going to work."},
			   {a:"Bureau", b:"Office / Desk", c:"Le bureau de Marie est fait en bois.", d:"Marie's desk is made of wood."},
			   {a:"Boîte de nuit", b:"Nightclub", c:"Je voudrais aller danser à la boîte de nuit!", d:"I would like to go dancing at the nightclub!"},
			   {a:"Mais", b:"But", c:"Je voudrais nager, mais il ne fait pas assez chaud aujourd'hui.", d:"I would like to swim, but it's not hot enough today."},
			   {a:"Savoir", b:"To know", c:"Savoir les nouvelles peut aider la conversation.", d:"To know the news can help with conversation."},
			   {a:"Suivre", b:"To follow", c:"Je préférerais suivre votre exemple.", d:"I would prefer to follow your lead."},
			   {a:"Parler", b:"To speak", c:"J'aime bien parler avec mes copains.", d:"I like to speak with my friends."},
			   {a:"Croire", b:"To believe", c:"Je préfère croire le meilleur des gens.", d:"I prefer to believe the best in people."},
			   {a:"Comment", b:"How", c:"Est-ce que tu connais comment faire ça?", d:"Do you know how to do that?"},
			   {a:"Jamais", b:"Never", c:"Elle ne fait jamais ça.", d:"She never does that."},
			   {a:"Attendre", b:"To wait", c:"Il ne sais pas comment attendre.", d:"He doesn't know how to wait."},
			   {a:"Donner", b:"To give", c:"Ils aiment bien donner des cadeaux à leur famille.", d:"They like to give gifts to their family."},
			   {a:"Toujours", b:"Always", c:"Cette forêt est toujours belle.", d:"This forest is always beautiful."},
			   {a:"Maintenant", b:"Now", c:"Il faut que vous le faites maintenant.", d:"It's necessary that you do it now."},
			   {a:"Demander", b:"To ask", c:"Je préfère ne pas demander.", d:"I prefer not to ask."},
			   {a:"Blague", b:"Joke", c:"Il raconte souvent des blagues très drôles.", d:"He often tells very funny jokes."},
			   {a:"Traverser", b:"To cross", c:"On va traverser la rue bientôt.", d:"We are going to cross the street soon."},
			   {a:"Probablement", b:"Probably", c:"C'est probablement trop près de la télévision.", d:"It's probably too close to the television."},
			   {a:"Voleur", b:"Thief", c:"Faites attention. C'est un voleur!", d:"Be careful. He's a thief!"},
			   {a:"Maladie", b:"Illness / Disease", c:"Il a une maladie très rare.", d:"He has a very rare disease."},
			   {a:"Cascade", b:"Waterfall", c:"Peux-tu vois la cascade?", d:"Can you see the waterfall?"},
			   {a:"Levure", b:"Yeast", c:"La levure est un ingredient important pour la fabrication de la biere.", d:"Yeast is an important ingredient for making beer."},
			   {a:"Cassé", b:"Broken", c:"Mince! L'assiette est completement cassé.", d:"Dang! The plate is completely broken."},
			   {a:"Chèvre", b:"Goat", c:"Le fromage de chèvre est vraiment bon!", d:"Goat's cheese is really good."}
			   /*{a:"Arrête", b:"Stop", c:"", d:""},
			   {a:"Prend", b:"Take", c:"", d:""},
			   {a:"Bête", b:"Beast", c:"", d:""},
			   {a:"Cherche", b:"Look / Search", c:"", d:""},
			   {a:"Tomber", b:"To fall", c:"", d:""},
			   {a:"Quelque chose", b:"Something", c:"", d:""},
			   {a:"Gorge", b:"Throat", c:"", d:""},
			   {a:"Bois", b:"Wood", c:"", d:""},
			   {a:"Forêt", b:"Forest", c:"", d:""},
			   {a:"Ange", b:"Angel", c:"", d:""},
			   {a:"Brindille", b:"Twig", c:"", d:""},
			   {a:"Brûler", b:"To burn", c:"", d:""},
			   {a:"Câlin", b:"Hug", c:"", d:""},
			   {a:"Coquillage", b:"Seashell", c:"", d:""},
			   {a:"Croquis", b:"Sketch", c:"", d:""},
			   {a:"Doux", b:"Soft", c:"", d:""},
			   {a:"Grelotter", b:"To shiver", c:"", d:""},
			   {a:"Orage", b:"Storm", c:"", d:""},
			   {a:"Myrtille", b:"Blueberry", c:"", d:""},
			   {a:"Noix de coco", b:"Coconut", c:"", d:""},
			   {a:"Voix", b:"Voice", c:"", d:""},
			   {a:"Etoile", b:"Star", c:"", d:""},
			   {a:"Pastèque", b:"Watermelon", c:"", d:""},
			   {a:"Plonger", b:"To dive", c:"", d:""},
			   {a:"Papillon", b:"Butterfly", c:"", d:""},
			   {a:"Sirène", b:"Mermaid", c:"", d:""},
			   {a:"Pluie", b:"Rain", c:"", d:""},
			   {a:"Tournesol", b:"Sunflower", c:"", d:""},
			   {a:"Briller", b:"To shine", c:"", d:""},
			   {a:"Pétillante", b:"Sparkling", c:"", d:""},
			   {a:"Chanceux", b:"Lucky", c:"", d:""},
			   {a:"Sourire", b:"Smile", c:"", d:""},
			   {a:"Argent", b:"Silver", c:"", d:""},
			   {a:"Bijoux", b:"Jewellery", c:"", d:""},
			   {a:"Bonbon", b:"Lolly / Candy", c:"", d:""},
			   {a:"Chagrin", b:"Grief", c:"", d:""},
			   {a:"Chouchou", b:"Darling", c:"", d:""},
			   {a:"Chou", b:"Cabbage", c:"", d:""},
			   {a:"Coquelicot", b:"Poppy", c:"", d:""},
			   {a:"Incroyable", b:"Incredible", c:"", d:""},
			   {a:"Magnifique", b:"Magnificent", c:"", d:""},
			   {a:"Mélange", b:"Mixture", c:"", d:""},
			   {a:"Parapluie", b:"Umbrella", c:"", d:""},
			   {a:"Soirée", b:"Evening", c:"", d:""},
			   {a:"Amour", b:"Love", c:"", d:""},
			   {a:"Parfum", b:"Perfume", c:"", d:""},
			   {a:"Alliance", b:"Wedding ring", c:"", d:""},
			   {a:"Lune de miel", b:"Honeymoon", c:"", d:""},
			   {a:"Mari", b:"Husband", c:"", d:""},
			   {a:"Copain", b:"Boyfriend / Friend", c:"", d:""},
			   {a:"Copine", b:"Girlfriend / Friend", c:"", d:""},
			   {a:"Galocher", b:"To French kiss", c:"", d:""},
			   {a:"Bricolage", b:"DIY", c:"", d:""},
			   {a:"Quincaillerie", b:"Hardware shop", c:"", d:""},
			   {a:"Formidable", b:"Excellent", c:"", d:""},
			   {a:"Rabibocher", b:"To get back together", c:"", d:""},
			   {a:"Aspirateur", b:"Vacuum cleaner", c:"", d:""},
			   {a:"Vachement", b:"Really / Very", c:"", d:""},
			   {a:"Pompette", b:"Tipsy", c:"", d:""},
			   {a:"Rouflaquettes", b:"Sideburns", c:"", d:""},
			   {a:"Dégoûtant", b:"Disgusting", c:"", d:""},
			   {a:"Encore", b:"Again", c:"", d:""},
			   {a:"En fait", b:"Actually", c:"", d:""},
			   {a:"Déchetterie", b:"Dump / Tip", c:"", d:""},
			   {a:"Inoubliable", b:"Unforgettable", c:"", d:""},
			   {a:"Bonheur", b:"Happiness", c:"", d:""},
			   {a:"Qui", b:"Who", c:"", d:""},
			   {a:"Avant", b:"Before", c:"", d:""},
			   {a:"Après", b:"After", c:"", d:""},
			   {a:"Même", b:"Same", c:"", d:""},
			   {a:"Autrefois", b:"Another time", c:"", d:""},
			   {a:"Autrement", b:"Otherwise", c:"", d:""},
			   {a:"Moins", b:"Less", c:"", d:""},
			   {a:"Aucune (f)", b:"None", c:"", d:""},
			   {a:"Heure", b:"Hour", c:"", d:""},
			   {a:"Falloir", b:"To require", c:"", d:""},
			   {a:"Raison", b:"Right / Reason", c:"", d:""},
			   {a:"Notre", b:"Our", c:"", d:""},
			   {a:"Mondial", b:"Global", c:"", d:""},
			   {a:"Alors", b:"Then / So", c:"", d:""},
			   {a:"D'accord", b:"Okay", c:"", d:""},
			   {a:"Trouvé", b:"Found", c:"", d:""},
			   {a:"Partagé", b:"Shared", c:"", d:""},
			   {a:"Viens", b:"Come", c:"", d:""},
			   {a:"Pendant", b:"During", c:"", d:""},
			   {a:"Laquelle (f)", b:"Which / Who", c:"", d:""},
			   {a:"Rester", b:"To stay", c:"", d:""},
			   {a:"Porter", b:"To wear / To carry", c:"", d:""},
			   {a:"Là", b:"There / Here", c:"", d:""},
			   {a:"Lieu", b:"Place", c:"", d:""},
			   {a:"Côté", b:"Side", c:"", d:""},
			   {a:"Ensemble", b:"Together", c:"", d:""},
			   {a:"Seulement", b:"Only", c:"", d:""},
			   {a:"Cas", b:"Case", c:"", d:""},
			   {a:"Puits", b:"Well (noun)", c:"", d:""},
			   {a:"Canicule", b:"Heatwave", c:"", d:""},
			   {a:"Mis à jour", b:"Updated", c:"", d:""},
			   {a:"Colis", b:"Parcel", c:"", d:""},
			   {a:"Douane", b:"Customs (airport)", c:"", d:""},
			   {a:"Coccinelle", b:"Ladybug / Ladybird", c:"", d:""}
			   */
			   ];


var colours = ["#365577","#808080","#388E8E","#5CACEE","#F7B3DA","#4A4A4A","#FFA54F","#FFB90F","#E8A87C","#8D8741","#8EE4AF","#0375B4",
               "#007849","#373737","#07889B","#66B9BF","#6D7993","#8FE388","#4CB944","#F5EE9E","#FCEC52","#CFFFB3",
               "#591F0A","#0267C1","#FFF275","#6699CC","#35605A","#31E981","#E65F5C","#A9C5A0","#C6DEC6","#020402",
               "#1D2D44","#748CAB","#8E4A49","#668586","#A7ACD9","#93C6D6","#0B3948","#416165","#D3AB9E","#EAC9C1","#D6F49D",
               "#CBA328","#A2D3C2","#122932","#2C514C","#BDE4A7","#7A9CC6","#A63446","#7E1946","#0C6291","#03254E","#1098F7",
               "#FCE181","#CCCCCC","#2D5F5D","#265077","#844D36","#77A6F7","#D3E3FC","#9E5A63","#97AABD","#479761","#19181A","#F78888",
               "#AD8350","#764134","#AFA060","#4E8098","#0B5351","#092327","#597081","#36494E","#A77E58","#BA3F1D","#7EA0B7","#8DAB7F",
               "#394032","#1E2019","#587B7F","#35A7FF","#FF5964","#84A98C","#69747C","#545454","#84DD63","#BEB0A7","#040303",
               "#8B9D83","#470024","#2C5784","#226CE0","#129490","#4281A4","#FE938C","#E6B89C","#D56F3E","#3C787E","#E3B505",
               "#764134","#AD8350","#585481","#C49BBB","#19297C","#D1BCE3","#C49BBB","#1C5253","#C3EB78","#B6174B","#306B34",
               "#2A3D45","#C17C74","#7FC6A4","#5D737E","#3C887E","#A17C6B","#CEB5A7","#FF9505","#353531","#F2E86D","#E85F5C",
               ];
